/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sea_turtle.glb 
Author: C.J..Goldman (https://sketchfab.com/C.J..Goldman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sea-turtle-442800e6cfe0447ba51327f863c45d7e
Title: Sea turtle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sea_turtle.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.defaultMat_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/sea_turtle.glb')
